spring:
    application:
        name: training-report
    activemq:
        broker-url: ${BROKER_URL}
        user: ${ACTIVEMQ_USER}
        password: ${ACTIVEMQ_PASSWORD}
        non-blocking-redelivery: true
        pool:
          max-connections: 10
          idle-timeout: 30000
        packages:
           trust-all: true
    data:
        mongodb:
          host: ${DB_HOST}
          port: ${DB_PORT}
          database: ${DB_NAME}
server:
    port: ${SERVER_PORT}
#eureka:
#    client:
#        serviceUrl:
#            defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
#    instance:
#        preferIpAddress: true
logging:
    pattern:
        console: '%d{HH:mm:ss.SSS} [%t] %-5level %logger{36} - %X{transactionId} - %msg%n'